from gym_wmgds.envs.toy_text.blackjack import BlackjackEnv
from gym_wmgds.envs.toy_text.roulette import RouletteEnv
from gym_wmgds.envs.toy_text.frozen_lake import FrozenLakeEnv
from gym_wmgds.envs.toy_text.nchain import NChainEnv
from gym_wmgds.envs.toy_text.hotter_colder import HotterColder
from gym_wmgds.envs.toy_text.guessing_game import GuessingGame
from gym_wmgds.envs.toy_text.kellycoinflip import KellyCoinflipEnv
from gym_wmgds.envs.toy_text.kellycoinflip import KellyCoinflipGeneralizedEnv
from gym_wmgds.envs.toy_text.cliffwalking import CliffWalkingEnv
from gym_wmgds.envs.toy_text.taxi import TaxiEnv
from gym_wmgds.envs.toy_text.guessing_game import GuessingGame
from gym_wmgds.envs.toy_text.hotter_colder import HotterColder
